// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzkltaljucynhpdqrlqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6a2x0YWxqdWN5bmhwZHFybHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mzc1MjIsImV4cCI6MjA2MjIxMzUyMn0.pWwZg6CKtkOEuvr2JwGZpFIpSJzwZogLqPwQhWqczBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);